name: Build and Release Windows Binary

on:
  push:
    tags:
      - '*' # Trigger on any tag push

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller urllib3
        pip install git+https://github.com/AIOpsTiger/pyairwave.git

    - name: Build executable
      run: |
        pyinstaller --onefile export_to_mremoteng.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/export_to_mremoteng.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
