name: Build and Release Windows Binary
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - '*' # Trigger on any tag push

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install git+https://github.com/eduardomozart/pyairwave.git

    - name: Inject Version
      run: |
        (Get-Content export_to_mremoteng.py) -replace 'VERSION = "DEV_BUILD"', "VERSION = `"${{ github.ref_name }}`"" | Set-Content export_to_mremoteng.py

    - name: Build executable
      run: |
        pyinstaller --onefile --name export_to_mremoteng-x64 export_to_mremoteng.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/export_to_mremoteng-x64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
